endpoint:
  url: https://docker-alln-01.cisco.com/status
  method: GET
  timeout: 0.010
  expectation:
    - type: HTTP_STATUS
      status: 200
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: .*<body>.*
cachet:
  api_url: http://cachet/api/v1/
  token: k2JRlAsuvCce0a9JjxDk
  component_id: 00
  #metric_id: 00
  create_incident: true
frequency: 30
