endpoint:
  url: "${URL}"
  method: "${METHOD}"
  timeout: "${TIMEOUT}"
  expectation:
    - type: "${TYPE1}"
      status: "${STATUS1}"
    - type: "${TYPE2}"
      threshold: "${THRESHOLD}"
    - type: "${TYPE3}"
      regex: "${REGEX}"
cachet:
  api_url: "${API_URL}"
  token: "${TOKEN}"
  component_id: "${COMPONET_ID}"
  #metric_id: "${METRIC_ID}"
  create_incident: "${CREATE_INCIDENT}"
frequency: "${FREQUENCY}"
