endpoint:
  url: "#{ENV['URL']}"
  method: "#{ENV['METHOD']}"
  timeout: "#{ENV['TIMEOUT']}"
  expectation:
    - type: "#{ENV['TYPE1']}"
      status: "#{ENV['STATUS1']}"
    - type: "#{ENV['TYPE2']}"
      threshold: "#{ENV['THRESHOLD']}"
    - type: "#{ENV['TYPE3']}"
      regex: "#{ENV['REGEX']}"
cachet:
  api_url: "#{ENV['API_URL']}"
  token: "#{ENV['TOKEN']}"
  component_id: "#{ENV['COMPONET_ID']}"
  #metric_id: "#{ENV['METRIC_ID']}"
  create_incident: "#{ENV['CREATE_INCIDENT']}"
frequency: "#{ENV['FREQUENCY']}"
