endpoint:
  url: ${URL_2_TEST}
  method: GET
  timeout: 0.10
  expectation:
    - type: HTTP_STATUS
      status: 200
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: ^
cachet:
  api_url: http://cachet/api/v1/
  token: eka92nYbLazeSdWyvUig
  component_id: ${COMPANENT_ID}
  #metric_id: 00
  create_incident: true
frequency: 30
